### PR TITLE
fix: account campaigns design

### LINKED ISSUE #287: Account campaigns page
**Describe the bug**
several glitches on account campaigns page

**fixes on account campaign page**
1. compare account campaigns with figma
2. make it look like designed
3. set correct link in account flyout to account/campaigns

### PR DESCRIPTION
**Pull request by hadi-ibra**
### closes #287 
---------------------

### Done:
- add default empty state for created campaign section
- update the data fetched for the campaign contributions
- updated styles for the campaign contributions table
- link flyout to account campaigns page

### CODE REVIEW

**Comment by 5-mark** [comment]
Campaign view:
image

Account campaign view:
image


@hadi-ibra please test your own stuff in a reasonable way. First thing I did is to compare Campaign Card in Campaigns list and Campaign Card in account. Its very much obvious that sth is wrong. The data to be shown are the same. 
I really questiion how we integrate these kind of things. Campaign cards should look always the same and contain the same information. Why cant we build once component which is used the same way everywhere?
@DarkNebula0: please check what goes wrong on code level.

**Comment by 5-mark** [comment]
@hadi-ibra also the campaign status badge is messed up again. its the wrong shape.

**Comment by hadi-ibra** [comment]
@5-mark I didn't update the campaign card it was a task done by @DarkNebula0, it wasn't part of the done tasks I put, and another thing is that the campaign card is component used every where, but I will check it .

**Comment by 5-mark** [comment]
@hadi-ibra or @DarkNebula0 (whoever built in the active status chip into the card), please have a look at a previous ticket:
https://github.com/gamedaoco/gamedao-haiku/issues/247
it says:
```
2. status chip on top left
2.1 When the campaign has the status Finalizing (3) or Success (5) show green status chip with corresponding status
2.2 When the campaign has the status Reverting (4) or Failed (6) show red status chip with corresponding status
2.3 all other statuses will not result in a status chip.
```
But in this PR we can see an "active" status on the card:
image
Even not considering the right text color. 
Why that? please remove it. There was no ticket saying we need the active status in a chip.

**Comment by PAkhidue** [comment]
Please also resolve conflicts, thanks!

**Comment by hadi-ibra** [comment]
@PAkhidue I resolved all conflicts and the design issues are done, please review it when you have time

**Review by developer-sidani — APPROVED** [review]

**Pull request merged**
