### PR TITLE
feat/navigation

### LINKED ISSUE #69: [NAV] Top Navigation
## User Story
As GameDAO user I want to see most interesting links on the top navigation so I can access them from anywhere of the page easily.

## Acceptance Criteria

**Mobile**
1.  Shows top bar navigation which is sticky on scroll
1.1 On the left there are 3 dots which open the organisations sidebar [#70]
1.2 In the middle the logo is shown
1.3 The logo is linked to the app root url
1.4 On the right the wallet and burger navigation are shown
2. Wallet [#78]
2.1 When not connected there is a button shown
2.2 When connected the button turns into an avatar
2.3 Clicking on the avatar opens a the wallet flyout [#78]
3. Burger Navigation
3.1  Clicking on burger navigation opens side-panel from right to left
3.2. Navigation items are listed as follows
3.2.1. Link Organisations List Page with "Organisations" to "/app/organisations"
3.2.2. Link Campaigns List Page with "Campaigns" to "/app/campaigns"
3.3.3. Link "Quests" to "/app/quests"
3.3. At the bottom a helper text + button to the documentation is shown
3.4. Social media icons are shown at the very bottom linking to the corresponding plattforms

4. _Search bar not to be included yet_

## Additional Information

- part of EPIC: #68 

UI Mockups: https://www.figma.com/file/8xFCnDl6SlUOonFm1V20ne/?node-id=3%3A17
Design System: https://www.figma.com/file/5L4VE8EIhRVB6kfIB50zlT/Minimal-Web?node-id=1489%3A112412 

## How to test

1. a
2. b
3. c
12. d

### LINKED ISSUE #70: [NAV] Organisation Sidebar
## User Story

As user I want to see organisations which i am a member of, so I can easily select and switch between organisations

## Acceptance Criteria

1. A quick access bar listing organisations is in place (for all viewports)
1.1. all organisations the user is a any type of member / owner of are listed
1.2. the organisations are sorted alphabetical
1.3. **Desktop**: The sidebar is always visible. Fixed on the left side of the browser window
1.4. **Mobile**: The side bar is shown by clicking on the 3 dots sitting within the header component
1.4.1. When the sidebar is present, the page content is moved to the right by the width of the sidebar

2. clicking/tapping on one of the organisation logos highlights the clicked organisation and opens the organisation overview page
2.1. When organisation is selected the position of the avatar remains at the original position

3. The sidebare comes in following states:
3.1 No DAO: This is used when the connected wallet is no member / owner of any organisation. In this case the sidebar shows a plus circle which links to the dao creation page
3.1.1. if the user is not connected, a modal which can be closed appears and displays "Please connect your wallet."
3.2. DAOs listed: If one or more DAOs are listed they are shown at the beginning of the list followed by a separator line and the dao creation circle button
3.3. DAO with update: If a DAO has a notification (example new proposal) a small circle is shown on top of the DAO avatar (if the user has seen the news, the notification is gone)
3.4. Many DAOs: If the sidebar lists more organisations than there is available space, I can scroll vertically with the mouse or swipe with the finger through these organisations. The last item in the list is cut off and a gradient overlay is on top of the avatar to indicate the scroll
4. The sidebar is sticky and the footer will be right from the sidebar for both viewports

## Additional Information

- The Design in Figma are shown in desktop and mobile view and are _customized_ components.

UI Mockups: UI Mockups: https://www.figma.com/file/8xFCnDl6SlUOonFm1V20ne/?node-id=3%3A17
Design system: https://www.figma.com/file/5L4VE8EIhRVB6kfIB50zlT/Minimal-Web?node-id=1489%3A112412
- part of EPIC: #68 

## Interaction Example Mobile

https://user-images.githubusercontent.com/25332596/161392681-53e23072-58b1-41c5-b30c-a4192c5b5012.mov

## How to test

1. be not loggedin and interact with the side bar (click the + and receive modal with the message to connect your wallet) on mobile and desktop
2. be loggedin and no member of a DAO, click the + and get to the create organisation form on mobile and desktop
3. be loggedin an member of one DAO, click the DAO and see page content changing to the dao detail page and the url is updated
4. be loggedin and member of several DAOs, resize your screen and scroll the DAOs make sure everything looks like in the design on mobile and desktop, click on a DAO an make sure that the page content and url is updated

### PR DESCRIPTION
**Pull request by DarkNebula0**
- Closes #70
- Closes #69

### CODE REVIEW

**Review by 5-mark — CHANGES_REQUESTED** [review]
for #69:
1. ✅ 
1.1 ✅ 
1.2 ✅ 
1.3✅ 
1.4 ❌ the wallet is not visible on the top navigation on mobile 
eg. not connected:
image
or connected:
image

2.1 ❌ button is shown but its the old button (which is a text link)
2.2 ❌  button does not yet turn into an avatar
2.3 ❌ ⚠️  probably just not yet implemented?
3. ✅ 
3.1 ✅ 
3.2 ✅ ✅ ✅  
3.3 ✅ 
3.4 ✅ 

for #70:
1.
1.1 ✅ 
1.2 ✅
1.3 ✅
1.4 ✅
1.4.1 ❌  clicking on the 3 dots on mobile shows the sidebar but darkens the content area which should not be the case, instead the page content should move to the right by the width of the sidebar and the content should not be darkened.

2. ✅ 
2.1 ✅

3. ✅ 
3.1 ❌  plus circle seems to be in main font color (violet) and not how designed in figma (maybe no issue at all?) and does not link to the dao creation page, which should be the case
3.1.1 ✅  👏🏼 👏🏼 
3.2 ✅ 
3.3 ✅
3.4 ❌ last item has no gradient overlay which should act as the indication to scroll, however there is also a scrollbar which should not be there as the user scrolls within the sidebar as described.
image

Visual can be found here: https://www.figma.com/file/5L4VE8EIhRVB6kfIB50zlT/Design-System?node-id=1489%3A112412
see snapshot.org for reference regarding scrolling behaviour (make sure you are in enough DAOs)

4. ❌  the sidebar seems sticky and on desktop the footer is right from the sidebar but on mobile I cannot test it because of AC 1.4.1 issue

**Comment by DarkNebula0** [comment]
@5-mark 
1.4
2.1
2.2
2.3
-> Yes the wallet was intentionally omitted because there is a separate ticket for it 

3.1 ->
a) The FE is still waiting for the color adjustments from ux, so the buttons and the background still have a different colors.
b) There is no dao creation page at the moment so the button points to "/app/organizations".

3.4 @mikeplanzer Does the gradiant come from mui or did you added it as custom Component?

**Comment by 2075** [comment]
is the "responsive navigation" the one designed?
not sure if the current pattern is suitable for our needs.

**Comment by DarkNebula0** [comment]
> "responsive navigation"

Please be a little more specific.
Which navigation do you mean Topbar or the organization siedbar ?

**Comment by 2075** [comment]
in terms of mobile friendly the top nav, 
although the scrollbars in the sidebar are a bit strange, too. 🗡️

**Comment by DarkNebula0** [comment]
Are you up to date with the latest deployment? The scroll bar should actually no longer be displayed.

> other question: what are the dots doing, does it mean, any event happened or something specific?
Yes, currently there is no logic for notifications so every 2. dao is displayed with a notification

**Comment by mikeplanzer** [comment]
> 3.4 @mikeplanzer Does the gradiant come from mui or did you added it as custom Component?

@DarkNebula0, the gradient at the bottom of the scroll list is not part of the core mui elements. I would recommend to use primary background color fading into 100% transparency as per design. This way it's linked to the core BG and if we change that the gradient is adapted as well.

**Review by 5-mark — APPROVED** [review]
good to go 👍🏼

**Pull request merged**
