### PR TITLE
Treasury frontend implementation

### PR DESCRIPTION
**Pull request by EZAMN**
It should be hooked up to real data instead of mocking it.
Some changes should still take place to make it 100% like the figma design

### CODE REVIEW

**Comment by 5-mark** [comment]
@DarkNebula0 wen review?

**Comment by 2075** [comment]
hi!

thank you for the PR!

- added @cargre87 to review from ux perspective.
- please also merge master to resolve conflicts

image

- I suggest to add plus and minus signs to incoming or outgoing tx @cargre87 
- if we show e.g. 10 rows, shouldnt the card show all the content as well? @cargre87 
- we also need better icons for the currencies @cargre87 
- three dots useless a.t.m. please remove

image

- legend doubled
- legend could/should say `incoming` / `outgoing` @cargre87 

cc @5-mark

**Comment by 2075** [comment]
@cargre87 @EZAMN @DarkNebula0 what are the next steps here?

**Comment by cargre87** [comment]
> @cargre87 @EZAMN @DarkNebula0 what are the next steps here?

I did add my notes like you said, can be exe? -

**Comment by AlexisZero** [comment]
I uploaded some changes, let me know if we need more things fixed

**Comment by cargre87** [comment]
Figma-Style
Bildschirmfoto 2022-09-30 um 18 49 51

Fixes:
- Font Color -> Grey - more distance between number and total
Bildschirmfoto 2022-09-30 um 18 31 36

- Delete the whiteisch Background seen left - use our standard sortable table style (fixed by Andre)
Bildschirmfoto 2022-09-30 um 18 32 09
Bildschirmfoto 2022-09-30 um 18 34 57

- mhmm?
Bildschirmfoto 2022-09-30 um 18 32 15

- if clicked dont show gray active, delete blueisch boarder
Bildschirmfoto 2022-09-30 um 18 53 21

- dont show pagination if there is no need for
Bildschirmfoto 2022-09-30 um 18 54 18

Miss from me, Icons for the currencies @2075 what the direction here? Use the public stuff, do we create a own set of it? Which one we need? - dont like to have a mixed public + own style here?

**Comment by 2075** [comment]
> Miss from me, Icons for the currencies @2075 what the direction here? Use the public stuff, do we create a own set of it? Which one we need? - dont like to have a mixed public + own style here?

lets collect icons and use just coloured pngs as placeholders for those where nothing is available.

**Comment by cargre87** [comment]
> > Miss from me, Icons for the currencies @2075 what the direction here? Use the public stuff, do we create a own set of it? Which one we need? - dont like to have a mixed public + own style here?
> 
> lets collect icons and use just coloured pngs as placeholders for those where nothing is available.

where do we get a complete list from?

**Comment by 2075** [comment]
> where do we get a complete list from?
voila:

- ZERO
- GAME
- PLAY
- aUSD
- USDT
- USDC
- DOT
- KSM
- ETH
- BTC

**Comment by cargre87** [comment]
> Figma-Style Bildschirmfoto 2022-09-30 um 18 49 51
> 
> Fixes:
> 
> * Font Color -> Grey - more distance between number and total
>   Bildschirmfoto 2022-09-30 um 18 31 36
> * Delete the whiteisch Background seen left - use our standard sortable table style (fixed by Andre)
>   Bildschirmfoto 2022-09-30 um 18 32 09
>   Bildschirmfoto 2022-09-30 um 18 34 57
> * mhmm?
>   Bildschirmfoto 2022-09-30 um 18 32 15
> * if clicked dont show gray active, delete blueisch boarder
>   Bildschirmfoto 2022-09-30 um 18 53 21
> * dont show pagination if there is no need for
>   Bildschirmfoto 2022-09-30 um 18 54 18
> 
> Miss from me, Icons for the currencies @2075 what the direction here? Use the public stuff, do we create a own set of it? Which one we need? - dont like to have a mixed public + own style here?

- Make them all same height 
Bildschirmfoto 2022-10-04 um 12 26 51

**Pull request closed without merging**
