### PR TITLE
chore: update packages

### PR DESCRIPTION
**Pull request by DarkNebula0**

### CODE REVIEW

**Comment by 2075** [comment]
image

**Comment by 2075** [comment]
computer says no

**Comment by DarkNebula0** [comment]
> computer says no @DarkNebula0

Yes comuter says, no more node 14 and vercel says we are waiting for aws and aws says it's currently being implemented -_-

So there will be no further updates until our env is switched to node16 ...

**Comment by 2075** [comment]
no bueno, aws, que pasa
https://github.com/aws/aws-lambda-base-images/issues/14
https://github.com/vercel/community/discussions/37

**Comment by DarkNebula0** [comment]
Merged with #121

**Pull request closed without merging**
