### PR TITLE
add types api route

### PR DESCRIPTION
**Pull request by 2075**

### CODE REVIEW

**Comment by 2075** [comment]
@DarkNebula0 @Persqual @soundyogi any news here?

**Comment by 5-mark** [comment]
@DarkNebula0 can you review this ticket?

**Comment by Persqual** [comment]
> the types should be derived from `@zeroio/type-definitions` and/or `@gamedao/types`

Currently we can't really use it BUT For later when we generate the schema.ts it will be really helpful, thanks for the idea.
We only need to look how we return the data because of the multiple networks we use - the "types" object will be different, right?

**Comment by 2075** [comment]
well, we can and have to use it, as it is current practice for all chains connectable through polkadotjs apps, we are using zero type def there as well and if we want to be connectable we need to maintain type packages and also use them ourselves, no?

also we need to add acala sdk to be able to query acala chains.

also check update in the issue here : https://github.com/gamedaoco/gamedao-haiku/issues/30 (wip)

**Comment by Persqual** [comment]
Ah, I missed that. Sure we can do it - we can simply JSON-Stringify those objects from the package and expose them to the frontend.

So who will maintain it in the future? I can also take that task over - but someone need to tell me how I can update it.

**Comment by 2075** [comment]
on the integration side you could have a look at how polkadotjs/apps does integrate it on type level.
in the future these packages eventually wont be neccessary due to type generation becoming automagical.

would be great if the person setting up the indexer now could also maintain the type packages.
otoh I used to generate new typings whenever the data structures changed when I changed the pallets, so both is possible.
I dont know though if all of this responsibility fits into available time, graphql, graphql indexer, type generation) also a question for @5-mark

**Comment by Persqual** [comment]
Yeah that's my main problem. I couldn't really start with the GraphlQl indexer subject because of my time.
Not sure, but maybe it's smarter, if anyone that has more time is doing that indexer (and maybe also someone that has more GraphQl experience).

I've the feeling that it will take me multiple weeks to finish that.

**Comment by 2075** [comment]
to set up an indexer there are existing instructions for subsquid and subquery. this can be done in a day or two and would help us all a lot.


https://github.com/PAIDNetwork/substrate-api-graphql

https://subsquid.io/

https://subquery.network/

**Comment by DarkNebula0** [comment]
@2075 @Persqual @5-mark 

Do we still need this or can it be removed?

**Comment by sniper365** [comment]
No. I don't need those. Thanks

**Pull request closed without merging**
