### PR TITLE
2075/graph

### PR DESCRIPTION
**Pull request by 2075**
example graphql
- pages/api/graph
- has graphiql enabled in dev
- one file example with queries, types, resolvers

### CODE REVIEW

**Comment by 2075** [comment]
@DarkNebula0 whats happening here?

**Comment by 2075** [comment]
@Persqual @soundyogi @DarkNebula0 any news on the review? we should move forward here.

**Comment by 5-mark** [comment]
@DarkNebula0: can you please review this ticket?

**Review by Persqual — APPROVED** [review]
For now it's fine - but we should definitely refactor:
- Remove the REST Endpoints
- Outsource types/resolvers to another package
- Generate the typeDefs string automatically therefore we have also Typescript (This one looks pretty cool: https://github.com/MichalLytek/type-graphql)

If we don't do that we just recreate the beta repo probably.

**Comment by 2075** [comment]
- rest endpoints will exist in the future because there will be data sources which will be just rest and exposed to a resolver. like this we keep independence.
- outsource types and resolvers can only take place when we have a reliable build coming from a monorepo in vercel using other packages, but definitely ack
- type generation is already part of the polkadotjs examples, we should also work on a package which auto generates types when a new node / runtime is released
-

**Comment by PAkhidue** [comment]
I don't understand the first point - could you explain it a bit more?

As far as I see that the GraphlQl endpoint is doing exactly the same as the REST endpoint. They both load global and local .json files and expose them.

So somewhere we need to "hardwire" it - and I would prefer to do that via GraphlQl when we already implemented it.
There should be no need for a mix of REST and GraphlQl but maybe I'm just missing something.

**Comment by Persqual** [comment]
> * rest endpoints will exist in the future because there will be data sources which will be just rest and exposed to a resolver. like this we keep independence.
> * outsource types and resolvers can only take place when we have a reliable build coming from a monorepo in vercel using other packages, but definitely ack
> * type generation is already part of the polkadotjs examples, we should also work on a package which auto generates types when a new node / runtime is released

I don't understand the first point - could you explain it a bit more?

As far as I see that the GraphlQl endpoint is doing exactly the same as the REST endpoint. They both load global and local .json files and expose them.

So somewhere we need to "hardwire" it - and I would prefer to do that via GraphlQl when we already implemented it.
There should be no need for a mix of REST and GraphlQl but maybe I'm just missing something.

**Comment by 2075** [comment]
- frontend facing -> graphql
- behind that many different systems and apis
- all unneeded homegrown REST apis will be removed at a certain point
- there will be future apis which are delivered as REST, be aware

**Pull request merged**
