### PR TITLE
feat(network-switch): add network switch

### LINKED ISSUE #166: Add ZERO Networks to Network Switch
## User Story

As user I want to have a stable enough environment where I can test the product and can rely that my created objects remain there unless announced differently.

## Acceptance Criteria

We have 4 chains running
1. local parachain  --> dev
2. parachain rococo --> stable
3. standalone beeblebrox --> dev
4. standalone alphaville --> stable

------ below this line old content of the ticket "network switch" ------

| ID | Name | Type | Graph | RPC |
|---|---|---|---|---|
| 1 | Development | Devnet Standalone | dev.graph.zero.io | dev.net.zero.io |
| 2 | Staging | Staging Standalone | staging.graph.zero.io | staging.net.zero.io |
| 3 | Development Parachain | Development Parachain | graph.dev.para.sub.zero.io | wss://node.dev.para.sub.zero.io |
| 4 | Staging Parachain | Rococo Parachain | staging.para.graph.zero.io | wss://staging.para.sub.zero.io |
| 5 | Live | Polkadot Parachain | graph.zero.io | net.zero.io |

## Additional Information

- 

## How to test

1. see network switch ( top bar or flyout )
2. select a network
3. content changes according to the selected network

### PR DESCRIPTION
**Pull request by DarkNebula0**
closes #166

### CODE REVIEW

**Comment by 5-mark** [comment]
could connect to local network: 
image

✅

**Review by PAkhidue — APPROVED** [review]

**Comment by 2075** [comment]
@cargre87 lets discuss where we should show the network switch

**Comment by 5-mark** [comment]
@DarkNebula0 when selecting a network which cannot be connected to and receiving an error toast I cannot close the network selection layer.

reproduce: select Rococo, receive error, try to close the layer by clicking on X. --> doesnt close

**Review by PAkhidue — DISMISSED** [review]

**Comment by 2075** [comment]
image

macos / brave with talisman wallet and two active accounts

**Review by PAkhidue — APPROVED** [review]

**Pull request merged**
