### PR TITLE
new wallet connect

### LINKED ISSUE #44: Wallet Connect
## User Story
As user I want to connect my wallet with gamedao so I can interact with the app

## Acceptance Criteria

1. The connect button contains "connect wallet"
2. Clicking the button leads to a modal:
2.1. If no polkadot.js or talisman wallet is installed the modal title says "No wallet found" and a list of wallets appear which can be installed (see Screenshot 1)
2.2. The listed wallets link to the corresponding pages (see links in Additional Information)
3. If at least one wallet is installed the same modal appears with the title "Select wallet" (see Screenshot 2)
3.1. The installed wallets are linking to connect the wallet
3.2 The not installed wallets are linking to the corresponding wallets (see links in Additional information)  
4. external links always open in a new tab
5. when the users wallet is connected the modal closes and the connect button is replaced by the wallet component

## Additional Information

Screenshots are to be understood as example and not as final designs

Screenshot 1:
image

Screenshot 2:
image

Screenshot 3 (when both wallets installed):
image

Screenshot 4 (illustration how iconography could look like):
image

### Wallet Links
Link Polkadot.js wallet: https://polkadot.js.org/extension/
Link Talisman wallet: https://talisman.xyz/
We do not link directly to the corresponding extension store of the browser, so that we dont have to update links if they change in the future.

###Process View
image

## How to test

1. have no wallet installed (eg. inkognito tab) and click connect button 
2. run through 2.1 & 2.2
3. have polkadot.js installed 
4. run through 3, 3.1, 3.2
5. check all links (also if the open in new tab)
6. when connected see modal closing and wallet component 

## Link to UI in Figma 
https://www.figma.com/file/8xFCnDl6SlUOonFm1V20ne/?node-id=3%3A15

### LINKED ISSUE #78: [NAV] Wallet Button + Flyout
## User Story
As GameDAO user I want to see my wallet connect status in the top navigation including links so I can access/see them from anywhere of the page easily.

## Acceptance Criteria

**Mobile**
1. The top navigation shows the wallet connect option [#69]
1.1. If user is not connected, a button is shown which triggers the wallet connect [#44]
1.2. If connected the button turn into an avatar 
1.2.1 if the onchain identity email is set and a gravatar image exists for the email the gravatar is shown
1.2.2 if not a fallback image is set (see figma)
1.3. Clicking the avatar triggers the wallet flyout

**Desktop**

2. The top navigation shows the wallet connect option [#69]
2.1. If user is not connected, a button is shown which triggers the wallet connect [#44]
2.2. If connected the button turn into the connected button state showing following information:
2.2.1 The avatar is shown on the left
2.2.2 In the middle the account name and account hash are shown
2.2.3 If account is verified, a verified icon is shown in front of the hash
2.2.4 If account is not verified, no icon is shown
2.2.5 on the right an dropdown button is shown which triggers the wallet flyout

**Mobile + Desktop**

3. Both mobile and desktop show a flyout which includes following elements
3.1. The connected wallet is shown as a card including the avatar, name, verification icon and hash
3.2. the connected wallet can be changed by clicking the change button on the card
3.3. Clicking the wallet change button closes the flyout and triggers a modal box listing all available wallets
3.4. A box with your transferable balances are shown corresponding to the selected network
3.5. An account navigation is shown linking to the dashboard and various subpages of the account page
3.6. At the bottom the currently selected network is shown
3.7. Clicking on the network or the 3 dots closes the flyout and triggers a modal box listing all available networks

## Additional Information

UI Mockups: https://www.figma.com/file/8xFCnDl6SlUOonFm1V20ne/?node-id=3%3A17
Design: https://www.figma.com/file/5L4VE8EIhRVB6kfIB50zlT/Minimal-Web?node-id=1489%3A112412

## How to test

1. a
3. b
5. c
6. d

### LINKED ISSUE #81: [Network] Network selector to connect to different testnets
## User Story
as a user i want to connect to different networks to access individual protocols and features

## Acceptance Criteria

1. show network connector
2. on click show networks
3. on select switch to network

## How to test

1. see
2. click
3. select
4. success

### PR DESCRIPTION
**Pull request by DarkNebula0**
- Closes #78
- Closes #44 
- Closes #81

### CODE REVIEW

**Review by 5-mark — APPROVED** [review]
The top navigation shows the wallet connect option  ✅ 
1.1. If user is not connected, a button is shown which triggers the wallet connect ✅ 
1.2. If connected the button turn into an avatar ✅ 
1.2.1 if the onchain identity email is set and a gravatar image exists for the email the gravatar is shown (⚠️ not tested)
1.2.2 if not a fallback image is set (see figma) ( ⚠️  not tested)
1.3. Clicking the avatar triggers the wallet flyout ✅ 

2. The top navigation shows the wallet connect option  ✅ 
2.1. If user is not connected, a button is shown which triggers the wallet connect ✅ 
2.2. If connected the button turn into the connected button state showing following information:
2.2.1 The avatar is shown on the left
2.2.2 In the middle the account name and account hash are shown ✅ 
2.2.3 If account is verified, a verified icon is shown in front of the hash ❌  icon is always shown  
2.2.4 If account is not verified, no icon is shown ❌  icon is always shown 
2.2.5 on the right an dropdown button is shown which triggers the wallet flyout ✅ 

3. Both mobile and desktop show a flyout which includes following elements ✅ 
3.1. The connected wallet is shown as a card including the avatar, name, verification icon and hash ✅ 
3.2. the connected wallet can be changed by clicking the change button on the card ✅ 
3.3. Clicking the wallet change button closes the flyout and triggers a modal box listing all available wallets ✅ 
3.4. A box with your transferable balances are shown corresponding to the selected network ✅ 
3.5. An account navigation is shown linking to the dashboard and various subpages of the account page ✅ 
3.6. At the bottom the currently selected network is shown ✅ 
3.7. Clicking on the network or the 3 dots closes the flyout and triggers a modal box listing all available networks ✅ 


ℹ️  The identity icon should be set when any onchain identity is set. When no onchain identity is set no icon should be shown.

@mikeplanzer : please also add review

**Comment by mikeplanzer** [comment]
Dear @DarkNebula0 , please find below my review (only mentioning where I found something, everything else can be seen as validated.

#78 - Wallet Button + Flyout
---
**1.1. If user is not connected, a button is shown which triggers the wallet connect** 
_ℹ️  Should be a button, not only text link_ 

**2.2.2 In the middle the account name and account hash are shown**
_ℹ️  Hash should be shortened so that there is more space_ 
image

**3.2. the connected wallet can be changed by clicking the change button on the card** 
_ℹ️  Clicking on button doesn't do anything_

**3.3. Clicking the wallet change button closes the flyout and triggers a modal box listing all available wallets**
_ℹ️  Clicking on button doesn't do anything_

**3.4. A box with your transferable balances are shown corresponding to the selected network**
_ℹ️ Title "Balances" should be shown_
image


#44 - Wallet Button + Flyout
---
**2.1. If no polkadot.js or talisman wallet is installed the modal title says "No wallet found" and a list of wallets appear which can be installed** 
_ℹ️  Connect wallet button is now shown at all if no wallet is installed_


#81 - Network selector to connect to different testnets
---
✅

**Review by Persqual — APPROVED** [review]

**Review by 5-mark — APPROVED** [review]
good to go 🏁

**Comment by 5-mark** [comment]
@DarkNebula0 still found sth:
- when clicking on the wallet, the scrollbar disappears and the content jumps a bit to the left
- GAME & PLAY Balances are missing in the wallet view

**Pull request merged**
