### PR TITLE
ahmad/fix/account-identity-form

### PR DESCRIPTION
**Pull request by developer-sidani**

### CODE REVIEW

**Comment by 2075** [comment]
> _ No description provided. _

- what is this pull request about?
- how to test?

**Review by 5-mark — CHANGES_REQUESTED** [review]
@developer-sidani:

- the display name is empty but in polkadot.js apps its filled, the transaction actually deleted my display name onchain
- as previously discussed we need to have the validators in place for the different fields. 
It seems like only the email validator is implemented

please refer to following screenshots:
image

vs. 
image
- the clear identity button is inactive and i cannot clear my identity through the frontend.:
image

**Comment by 2075** [comment]
> 

I understand what this is meant to do, but there is no reference link to the view.

**Comment by 2075** [comment]
the location to see the actual work: https://gamedao-haiku-fmqkaznuz-75.vercel.app/app/account

**Comment by 2075** [comment]
image

- setting identity does not refresh the view, should be subscription
- set on-chain identity should only be shown when you have not set one previously
- name does not update when identity was set?

**Review by 2075 — CHANGES_REQUESTED** [review]
https://github.com/gamedaoco/gamedao-haiku/pull/223#issuecomment-1174154520

**Comment by developer-sidani** [comment]
> image
> 
> * setting identity does not refresh the view, should be subscription
> * set on-chain identity should only be shown when you have not set one previously
> * name does not update when identity was set?

@2075 I talked with @DarkNebula0 and we can change the identity query to subscription from the main branch, but for the sake of getting things done with the account page we will leave it as is

**Pull request merged**
